In [98]:
from typing import List
import math 
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
# from sklearn import preprocessing

In [99]:
columns_to_read = ['Similarity Score', 'Creation date', 'No. of Views', 
                   "No. of Likes on YouTube", "Rating on CourseMapper",
                   "No of. Save on CourseMapper"
                ]

df = pd.read_excel("factors ranking 2 (Responses).xlsx", usecols=columns_to_read)
# df.head(5)

In [100]:
def rename_label_rank(x):
    if x == "Rank 1":
        return 1
    elif x == "Rank 2":
        return 2
    elif x == "Rank 3":
        return 3
    elif x == "Rank 4":
        return 4
    elif x == "Rank 5":
        return 5
    elif x == "Rank 6":
        return 6

for name in df.columns.values:
   df[name] = df[name].apply(lambda x: rename_label_rank(x))

df.head(5)

,Similarity Score,Creation date,No. of Views,No. of Likes on YouTube,Rating on CourseMapper,No of. Save on CourseMapper
0,1,3,4,2,5,6
1,1,2,3,4,5,6
2,6,5,3,2,4,1
3,6,5,4,3,2,1
4,2,1,5,4,3,6

In [101]:
cols = {}
mean_scores = []

for name in df.columns.values:
    data = df[name].tolist()
    data_sum = sum(data)
    count  = len(data)
    cols[name] = {
        "data": data,
        "sum": data_sum,
        "mean_score": round((data_sum / count), 3)
    }
    mean_scores.append(round((data_sum / count), 3))

for v in cols.items():
    print(v)

mean_scores

('Similarity Score', {'data': [1, 1, 6, 6, 2], 'sum': 16, 'mean_score': 3.2})
('Creation date', {'data': [3, 2, 5, 5, 1], 'sum': 16, 'mean_score': 3.2})
('No. of Views', {'data': [4, 3, 3, 4, 5], 'sum': 19, 'mean_score': 3.8})
('No. of Likes on YouTube', {'data': [2, 4, 2, 3, 4], 'sum': 15, 'mean_score': 3.0})
('Rating on CourseMapper', {'data': [5, 5, 4, 2, 3], 'sum': 19, 'mean_score': 3.8})
('No of. Save on CourseMapper', {'data': [6, 6, 1, 1, 6], 'sum': 20, 'mean_score': 4.0})

[3.2, 3.2, 3.8, 3.0, 3.8, 4.0]

In [102]:
xxx

In [103]:
import numpy as np
from sklearn.preprocessing import normalize as normalize_sklearn, MinMaxScaler as MinMaxScaler_sklearn

def normalize_factor_weights(factor_weights: dict, method_type = "l1", complete=True): # List[float]
    """
    https://www.pythonprog.com/sklearn-preprocessing-normalize/#Normalization_Techniques
    TypeScript: https://sklearn.vercel.app/guide/install

    factor_weights = { 'similarity_score': 0.7, 'creation_date': 0.3, 'nbr_views': 0.3, 
            'nbr_likes_youTube': 0.1, 'rating_courseMapper': 0.1, 'nbr_save_courseMapper': 0.1
        }

    method_type: normalization techniques
        l1: L1 normalization, also known as L1 norm normalization or Manhattan normalization
        l1: L2 normalization, also known as L2 norm normalization or Euclidean normalization
        max: Max Normalization
        min-max: Min-Max
    """
    normalized_weights = None
    scaled_data = None
    
    weights = [value for key, value in factor_weights.items()]
    factor_names = [key for key, value in factor_weights.items()]

    if method_type == "l1":
        normalized_weights = normalize_sklearn([weights], norm=method_type).tolist()
    if method_type == "l2":
        normalized_weights = normalize_sklearn([weights], norm=method_type).tolist()
    if method_type == "max":
        normalized_weights = normalize_sklearn([weights], norm=method_type).tolist()
    if method_type == "min-max":
        data = np.array(weights).reshape(-1, 1)
        print(data)
        scaler = MinMaxScaler_sklearn()
        scaler.fit(data)
        scaled_data = scaler.transform(data)
        scaled_data = scaled_data.tolist()
        scaled_data = [value[0] for value in scaled_data]

    if normalized_weights:
        normalized_weights = normalized_weights[0]
        normalized_weights = [round(value, 3) for value in normalized_weights]
    elif scaled_data:
        normalized_weights = scaled_data

    if complete:
        normalized_weights = dict(zip(factor_names, normalized_weights))

    return normalized_weights

def get_factor_weight_by_scores_normalized(scores: list):
    sum_scores = sum(scores)
    weights_final = []
    for score in scores:
        cal = round((score / sum_scores), 3)
        weights_final.append(cal)
    return weights_final

In [104]:
weights = [0.5, 0.7, 0.9, 1, 0.3, 0.1]
weights = [1, 0.1, 0.1, 0.1, 0.1, 0.1]
weights = [0.7, 0.3, 0.3, 0.1, 0.1, 0.1]
factor_weights = { 'similarity_score': 0.7, 'creation_date': 0.3, 'nbr_views': 0.3, 
                'nbr_likes_youTube': 0.1, 'rating_courseMapper': 0.1, 'nbr_save_courseMapper': 0.1
            }

print(weights)
print()

print("l1")
normalized_weights = normalize_factor_weights(factor_weights=factor_weights, method_type="min-max", complete=False)
print(normalized_weights)
print(sum(normalized_weights))
print(get_factor_weight_by_scores_normalized(normalized_weights))
# print()

"""
print("l2")
normalized_weights = normalize_factor_weights(weights=weights, method_type="l2")
print(normalized_weights)
print(get_factor_weight_by_scores_normalized(normalized_weights))
print()

print("max")
normalized_weights = normalize_factor_weights(weights=weights, method_type="max")
print(normalized_weights)
print(get_factor_weight_by_scores_normalized(normalized_weights))
print()

print("min-max")
normalized_weights = normalize_factor_weights(weights=weights, method_type="min-max")
print(normalized_weights)
print(get_factor_weight_by_scores_normalized(normalized_weights))
print()
"""

[0.7, 0.3, 0.3, 0.1, 0.1, 0.1]

l1
[[0.7]
 [0.3]
 [0.3]
 [0.1]
 [0.1]
 [0.1]]
[1.0, 0.3333333333333333, 0.3333333333333333, 0.0, 0.0, 0.0]
1.6666666666666665
[0.6, 0.2, 0.2, 0.0, 0.0, 0.0]

'\nprint("l2")\nnormalized_weights = normalize_factor_weights(weights=weights, method_type="l2")\nprint(normalized_weights)\nprint(get_factor_weight_by_scores_normalized(normalized_weights))\nprint()\n\nprint("max")\nnormalized_weights = normalize_factor_weights(weights=weights, method_type="max")\nprint(normalized_weights)\nprint(get_factor_weight_by_scores_normalized(normalized_weights))\nprint()\n\nprint("min-max")\nnormalized_weights = normalize_factor_weights(weights=weights, method_type="min-max")\nprint(normalized_weights)\nprint(get_factor_weight_by_scores_normalized(normalized_weights))\nprint()\n'

In [105]:
xxx

NameError: name 'xxx' is not defined

In [ ]:
# import matplotlib.pyplot as plt
# from matplotlib.widgets import Slider

# # Create slider axes
# ax_slider = plt.axes([0.1, 0.1, 0.8, 0.05])  # [left, bottom, width, height]

# # Create slider
# # slider = Slider(ax_slider, 'Frequency', 0.1, 10.0, valinit=1.0)
# # slider = Slider(ax_slider, "", 0.1, 10.0, valinit=1.0)
# slider = Slider(ax_slider, 'Frequency', 0, 1, valinit=0.33)
# # plt.show()

In [ ]:
import matplotlib.pyplot as plt

def plot_progress_bar(percentage, bar_height=0.3):
    fig, ax = plt.subplots()
    ax.barh(0, percentage, color='skyblue', height=bar_height)
    
    # Add percentage label inside the bar
    ax.text(percentage / 2, 0, f"{percentage}%", ha='center', va='center', color='black', fontsize=12)

    # Customize the plot
    ax.set_xlim(0, 100)
    ax.set_ylim(-0.5, 0.5)
    ax.set_axis_off()

    # Show plot
    plt.show()

def progress_bar_from_factor_weights(weights: list, bar_height=0.1):
    for weight in weights:
        progress_percentage = weight * 100
        plot_progress_bar(progress_percentage, bar_height=bar_height)

# # Example usage:
# progress_percentage = 0.75 * 100
# plot_progress_bar(progress_percentage, bar_height=0.3)

# progress_bar_from_factor_weights(weights=normalized_weights)

In [ ]:
xxxxx

NameError: name 'xxxxx' is not defined

In [ ]:
## method 1: count occurrences


## method 2: sum and lower value is better

    # df.insert(0, 'User', range(0 + 1, 1 + len(df)))
    # df["User"] = df["User"].apply(lambda x: f"user {x}")
    # df.head(5)

    # df = pd.concat([df, pd.DataFrame([{}])], ignore_index=True)
    # df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)


def method2(df):
    sum_row = {} # {"User": "Sum"}
    for name in df.columns.values[0:]:
        sum_row[name] = df[name].sum()
    
    print(sum_row)

    # Find the item with the lowest value
    min_item: dict = min(sum_row.items(), key=lambda item: round(item[1], 2))
    print(min_item)

    min_abs_value = min_item[1]
    scores_normalized= []
    for key, value in sum_row.items():
        cal = round((value / min_abs_value), 3)
        scores_normalized.append(cal)

    print(scores_normalized)

    sum_scores_normalized = sum(scores_normalized)
    factors_weight = []
    for v in scores_normalized:
        cal = round((v / sum_scores_normalized), 3)
        factors_weight.append(cal)
    
    print(factors_weight)

    return df

r = method2(df) # .head(10)

{'Similarity Score': 16, 'Creation date': 16, 'No. of Views': 19, 'No. of Likes on YouTube': 15, 'Rating on CourseMapper': 19, 'No of. Save on CourseMapper': 20}
('No. of Likes on YouTube', 15)
[1.067, 1.067, 1.267, 1.0, 1.267, 1.333]
[0.152, 0.152, 0.181, 0.143, 0.181, 0.19]

In [ ]:
xx

NameError: name 'xx' is not defined

In [ ]:
cols_new_names = ["A", "B", "C", "D", "E", "F"]
cols_dict = {}
for i in range(len(columns_to_read)):
    cols_dict[columns_to_read[i]] = cols_new_names[i]

df.rename(columns=cols_dict, inplace = True)

In [ ]:
data = df.to_dict("records")

In [ ]:
# import numpy as np
# from scipy.stats import chi2_contingency

# # Sample data
# data = [
#     {'A': 1, 'B': 3, 'C': 4, 'D': 2, 'E': 5, 'F': 6},
#     {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6},
#     {'A': 6, 'B': 5, 'C': 3, 'D': 2, 'E': 4, 'F': 1},
#     {'A': 6, 'B': 5, 'C': 4, 'D': 3, 'E': 2, 'F': 1},
#     {'A': 2, 'B': 1, 'C': 5, 'D': 4, 'E': 3, 'F': 6}
# ]

# # Helper function to flatten the data into a single list
# def flatten_data(data):
#     flattened = []
#     for d in data:
#         flattened.extend(list(d.values()))
#     return flattened

# # Chi-Square Goodness of Fit Test
# def chi_square_goodness_of_fit(observed, expected):
#     chi_sq, p_value = chi2_contingency([observed, expected])[:2]
#     return chi_sq, p_value

# # Calculate observed frequencies
# observed_frequencies = np.array(flatten_data(data))
# observed_counts = np.bincount(observed_frequencies)

# # Chi-Square Goodness of Fit Test
# expected_frequency = len(observed_frequencies) / 6
# expected_counts = np.full_like(observed_counts, expected_frequency)
# chi_sq_goodness, p_value_goodness = chi_square_goodness_of_fit(observed_counts, expected_counts)

# # Print results
# print("Chi-Square Goodness of Fit Test:")
# print("observed_frequencies:", observed_frequencies)
# print("observed_counts:", observed_counts)
# print("expected_frequency:", expected_frequency)
# print("expected_counts:", expected_counts)
# print("")

# print("Chi-Square Statistic:", chi_sq_goodness)
# print("P-value:", p_value_goodness)
# print("")

In [ ]:
# cols = []
# for name in df.columns.values:
#     cols.append(df[name].values)

# cols

In [ ]:
# cols = [list(item.values()) for item in data]
# cols

# # Create a contingency table
# # observed = np.array([ss, cd, nv])
# observed = np.array(cols)

# # Perform the chi-square test
# chi2, p, dof, expected = chi2_contingency(observed)
# chi2, p, dof, expected
# print(chi2)
# print(p)
# print(dof)
# print(expected)

In [ ]:
xxxxxx

NameError: name 'xxxxxx' is not defined

In [ ]:
columns_to_read = ['No. of Views', 'Creation Date', 'Rating on CourseMapper', 
                   "Similarity Score", "No. of Saves on CourseMapper",
                   "Likes on YouTube"
                ]

df = pd.read_excel("factors ranking (Responses).xlsx", usecols=columns_to_read)
df.head(5)

,No. of Views,Creation Date,Rating on CourseMapper,Similarity Score,No. of Saves on CourseMapper,Likes on YouTube
0,More Importanrt,More Importanrt,Most Importanrt,Importanrt,Least Importanrt,Importanrt
1,Somewhat Importanrt,Most Importanrt,More Importanrt,Importanrt,Somewhat Importanrt,Least Importanrt
2,More Importanrt,More Importanrt,More Importanrt,More Importanrt,More Importanrt,Importanrt
3,Importanrt,Importanrt,Importanrt,Importanrt,Importanrt,More Importanrt

In [ ]:
# views = df["Which factors are most important in recommendation ? [Views]"].values

def update_value(x):
    x = str(x).strip().lower()

    if x == "least importanrt":
        return 1
    elif x == "somewhat importanrt":
        return 2
    elif x == "importanrt":
        return 3
    elif x == "more importanrt":
        return 4
    elif x == "most importanrt":
        return 5


for name in df.columns.values:
   df[name] = df[name].apply(lambda x: update_value(x))

df.insert(0, 'User', range(0 + 1, 1 + len(df)))
df["User"] = df["User"].apply(lambda x: f"user {x}")
df.head(5)

,User,No. of Views,Creation Date,Rating on CourseMapper,Similarity Score,No. of Saves on CourseMapper,Likes on YouTube
0,user 1,4,4,5,3,1,3
1,user 2,2,5,4,3,2,1
2,user 3,4,4,4,4,4,3
3,user 4,3,3,3,3,3,4

In [ ]:
#### Calculate Mean Score (Average)
nbr_user = df.shape[0]
avg_row = {"User": "Mean Score"}
for name in df.columns.values[1:]:
    avg_row[name] = float(df[name].sum() / nbr_user)

df = pd.concat([df, pd.DataFrame([{}])], ignore_index=True) # for empty row
df = pd.concat([df, pd.DataFrame([avg_row])], ignore_index=True)
df.head(10)

,User,No. of Views,Creation Date,Rating on CourseMapper,Similarity Score,No. of Saves on CourseMapper,Likes on YouTube
0,user 1,4.00,4.0,5.0,3.00,1.0,3.00
1,user 2,2.00,5.0,4.0,3.00,2.0,1.00
2,user 3,4.00,4.0,4.0,4.00,4.0,3.00
3,user 4,3.00,3.0,3.0,3.00,3.0,4.00
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Mean Score,3.25,4.0,4.0,3.25,2.5,2.75

In [ ]:
def normalize_mean_score(value, min_value, max_value):
    return (value - min_value) / (max_value - min_value)

def rescale_score_normalized(score, epsilon):
    return score * (1 - epsilon) + epsilon

del avg_row["User"]

# Find the item with the lowest value
min_item: dict = min(avg_row.items(), key=lambda item: round(item[1], 2))
# print("Item with lowest value:", min_item)

# Find the item with the highest value
max_item: dict = max(avg_row.items(), key=lambda item: round(item[1], 2))
# print("Item with highest value:", max_item)

min_value = min_item[1]
max_value = max_item[1]

sum_score_normalized = 0
sum_score_normalized2 = 0
scores_nonrmalized = []
scores_nonrmalized2 = []

sc = []
sc2 = []
for key, value in avg_row.items():
    score_nomrmalized = normalize_mean_score(value=value, min_value=min_value, max_value=max_value)
    score_rescaled = rescale_score_normalized(score=score_nomrmalized, epsilon=0.1)
    print(f"mean score: {value} and score normalized: {score_nomrmalized} and score rescaled: {score_rescaled}")
    
    sum_score_normalized += score_nomrmalized
    scores_nonrmalized.append(score_nomrmalized)

    sum_score_normalized2 += score_rescaled
    scores_nonrmalized2.append(score_rescaled)

print("-------------")
print(scores_nonrmalized)
print(scores_nonrmalized2)

print("-------------")
sv = 0
sv2 = 0
s = []
s2 = []
for score in scores_nonrmalized:
    v = round((score / sum_score_normalized), 2)
    s.append(v)
    sv += v

for score in scores_nonrmalized2:
    v = round((score / sum_score_normalized2), 2)
    s2.append(v)
    sv2 += v

print("------------")
print(f"{s}, sum: ", sum(s))
print(f"{s2}, sum: ", sum(s2))

mean score: 3.25 and score normalized: 0.5 and score rescaled: 0.55
mean score: 4.0 and score normalized: 1.0 and score rescaled: 1.0
mean score: 4.0 and score normalized: 1.0 and score rescaled: 1.0
mean score: 3.25 and score normalized: 0.5 and score rescaled: 0.55
mean score: 2.5 and score normalized: 0.0 and score rescaled: 0.1
mean score: 2.75 and score normalized: 0.16666666666666666 and score rescaled: 0.25
-------------
[0.5, 1.0, 1.0, 0.5, 0.0, 0.16666666666666666]
[0.55, 1.0, 1.0, 0.55, 0.1, 0.25]
-------------
------------
[0.16, 0.32, 0.32, 0.16, 0.0, 0.05], sum:  1.01
[0.16, 0.29, 0.29, 0.16, 0.03, 0.07], sum:  1.0

In [ ]:
for name in df.columns.values[1:]:
    print(name)

No. of Views
Creation Date
Rating on CourseMapper
Similarity Score
No. of Saves on CourseMapper
Likes on YouTube

In [ ]:
import math

def round_up_to_two_decimal_places(number):
    rounded_number = math.ceil(number * 100) / 100
    return rounded_number


max_abs_value = max_item[1]
s3 = []
for key, value in avg_row.items():
    cal = round((value / max_abs_value), 3)
    # cal = round_up_to_two_decimal_places(value / max_abs_value)
    s3.append(cal)

print(s3)

sum_s3 = sum(s3)
sw3 = []
for v in s3:
    cal = round((v / sum_s3), 3)
    cal = round_up_to_two_decimal_places(v / sum_s3)
    sw3.append(cal)

print(sw3)
sum(sw3)

[0.812, 1.0, 1.0, 0.812, 0.625, 0.688]
[0.17, 0.21, 0.21, 0.17, 0.13, 0.14]

1.03

In [ ]:
avg_row_s3 = avg_row
for i, key in enumerate(avg_row_s3):
    avg_row_s3[key] = s3[i]

avg_row_s3["User"] = "Normalized Score"
df = pd.concat([df, pd.DataFrame([avg_row_s3])], ignore_index=True)

In [ ]:
del avg_row["User"]
avg_row_sw3 = avg_row
for i, key in enumerate(avg_row_sw3):
    avg_row_sw3[key] = sw3[i]

avg_row_sw3["User"] = "factor weight"
df = pd.concat([df, pd.DataFrame([avg_row_sw3])], ignore_index=True)
df.head(10)

,User,No. of Views,Creation Date,Rating on CourseMapper,Similarity Score,No. of Saves on CourseMapper,Likes on YouTube
0,user 1,4.000,4.00,5.00,3.000,1.000,3.000
1,user 2,2.000,5.00,4.00,3.000,2.000,1.000
2,user 3,4.000,4.00,4.00,4.000,4.000,3.000
3,user 4,3.000,3.00,3.00,3.000,3.000,4.000
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Mean Score,3.250,4.00,4.00,3.250,2.500,2.750
6,Normalized Score,0.812,1.00,1.00,0.812,0.625,0.688
7,factor weight,0.170,0.21,0.21,0.170,0.130,0.140

In [ ]:
xxxxx

NameError: name 'xxxxx' is not defined

# First QA

In [ ]:
df = pd.read_excel("factors ranking (Responses)3.xlsx")

In [ ]:
df.head(5)

,Timestamp,What is your highest degree?,Are you familiar with recommendation content?,Which factors are most important in recommendation ? [Views],Which factors are most important in recommendation ? [Creation Date],Which factors are most important in recommendation ? [Rating],Which factors are most important in recommendation ? [Similarity Score],Which factors are most important in recommendation ? [Bookmark Count],Please rank the following factors in order of importance [Row 1]
0,1970-01-01 01:00:45,Bachelor&apos;s degree,Yes,Somewhat Important,Important,More Important,Most Important,Important,Column 1
1,1970-01-01 01:00:45,Master&apos;s degree,NaN,Important,Somewhat Important,Important,More Important,Somewhat Important,Column 1
2,1970-01-01 01:00:45,high school diploma,NaN,Important,Important,Important,Important,Important,Column 1
3,1970-01-01 01:00:45,high school diploma,NaN,Somewhat Important,Most Importanrt,More Important,Important,Most Important,Column 1

In [ ]:
views_counts = df["Which factors are most important in recommendation ? [Views]"].value_counts()
creation_date_counts = df["Which factors are most important in recommendation ? [Creation Date]"].value_counts()
rating_counts = df["Which factors are most important in recommendation ? [Rating]"].value_counts()
similarity_score_counts = df["Which factors are most important in recommendation ? [Similarity Score]"].value_counts()
bookmark_counts = df["Which factors are most important in recommendation ? [Bookmark Count]"].value_counts()

In [ ]:
views_counts_normalized = df["Which factors are most important in recommendation ? [Views]"].value_counts(normalize=True)
creation_date_counts_normalized = df["Which factors are most important in recommendation ? [Creation Date]"].value_counts(normalize=True)
rating_counts_normalized = df["Which factors are most important in recommendation ? [Rating]"].value_counts(normalize=True)
similarity_score_counts_normalized = df["Which factors are most important in recommendation ? [Similarity Score]"].value_counts(normalize=True)
bookmark_counts_normalized = df["Which factors are most important in recommendation ? [Bookmark Count]"].value_counts(normalize=True)

In [ ]:
def get_key_and_value_counts(value_counts: pd.core.series.Series):
    result = {}
    for k,v in value_counts.iteritems():
        result[k] = v
    return result


def get_key_and_value_counts_percent(value_counts: pd.core.series.Series, default_count=5):
    result = {}
    for k,v in value_counts.iteritems():
        result[k] = v / default_count
    return result

In [ ]:
print("Total User:", df.shape[0])
print("views:", get_key_and_value_counts(views_counts))
print("creation date:", get_key_and_value_counts(creation_date_counts))
print("rating:", get_key_and_value_counts(rating_counts))
print("similarity score:", get_key_and_value_counts(similarity_score_counts))
print("bookmark:", get_key_and_value_counts(bookmark_counts))

data = {
    "views": get_key_and_value_counts(views_counts),
    "creation_date": get_key_and_value_counts(creation_date_counts),
    "rating": get_key_and_value_counts(rating_counts),
    "similarity_score": get_key_and_value_counts(similarity_score_counts),
    "bookmark_count": get_key_and_value_counts(bookmark_counts),
}

Total User: 4
views: {'Somewhat Important': 2, 'Important': 2}
creation date: {'Important': 2, 'Somewhat Important': 1, 'Most Importanrt': 1}
rating: {'More Important': 2, 'Important': 2}
similarity score: {'Important': 2, 'Most Important': 1, 'More Important': 1}
bookmark: {'Important': 2, 'Somewhat Important': 1, 'Most Important': 1}

# Calculating the percentages for each question and order them

In [ ]:
def order_factors(data: dict, nbr_participant=0):
    result = {}
    for key, stats in data.items():
        factor = {}
        # factor = [{k: v} for k, v in stats.items()]
        for k, v in stats.items():
            factor[k] = (v / nbr_participant) # * 100

        values = [v for k, v in factor.items()]
        avr_sum = sum(values) / len(values)
        result[key] = avr_sum

        print(values)
        print(avr_sum)
        print()

    return result

order_factors(data=data, nbr_participant=4)

[0.5, 0.5]
0.5

[0.5, 0.25, 0.25]
0.3333333333333333

[0.5, 0.5]
0.5

[0.5, 0.25, 0.25]
0.3333333333333333

[0.5, 0.25, 0.25]
0.3333333333333333

{'views': 0.5,
 'creation_date': 0.3333333333333333,
 'rating': 0.5,
 'similarity_score': 0.3333333333333333,
 'bookmark_count': 0.3333333333333333}

In [ ]:
# print("Total User:", df.shape[0])
# print("views:", get_key_and_value_counts_percent(views_counts))
# print("creation date:", get_key_and_value_counts_percent(creation_date_counts))
# print("rating:", get_key_and_value_counts_percent(rating_counts))
# print("similarity score:", get_key_and_value_counts_percent(similarity_score_counts))
# print("bookmark:", get_key_and_value_counts_percent(bookmark_counts))

In [ ]:
# print("Total User:", df.shape[0])
# print("views:", get_key_and_value_counts_percent(views_counts_normalized))
# print("creation date:", get_key_and_value_counts_percent(creation_date_counts_normalized))
# print("rating:", get_key_and_value_counts_percent(rating_counts_normalized))
# print("similarity score:", get_key_and_value_counts_percent(similarity_score_counts_normalized))
# print("bookmark:", get_key_and_value_counts_percent(bookmark_counts_normalized))

# Second QA

In [ ]:
df2 = pd.read_excel("factors ranking (Responses)2.xlsx")
df2.head()

,Timestamp,What is your highest degree?,Are you familiar with recommendation content?,Which factors are most important in recommendation ? [Views],Which factors are most important in recommendation ? [Creation Date],Which factors are most important in recommendation ? [Rating],Which factors are most important in recommendation ? [Similarity Score],Which factors are most important in recommendation ? [Bookmark Count],Please rank the following factors in order of importance [Row 1]
0,2024-04-20 23:26:02.873,Bachelor's degree,Yes,2,1,4,3,5,Column 1
1,2024-04-20 23:33:09.033,Master's degree,NaN,1,2,4,5,3,Column 1
2,2024-04-20 23:33:45.276,high school diploma,NaN,3,2,1,5,4,Column 1
3,2024-04-20 23:34:09.648,high school diploma,NaN,2,3,4,1,5,Column 1

In [ ]:
def position_str(x):
    return f"position({x})"

In [ ]:
df2["Which factors are most important in recommendation ? [Views]"] = df2["Which factors are most important in recommendation ? [Views]"].apply(lambda x: position_str(x))
df2["Which factors are most important in recommendation ? [Creation Date]"] = df2["Which factors are most important in recommendation ? [Creation Date]"].apply(lambda x: position_str(x))
df2["Which factors are most important in recommendation ? [Rating]"] = df2["Which factors are most important in recommendation ? [Rating]"].apply(lambda x: position_str(x))
df2["Which factors are most important in recommendation ? [Similarity Score]"] = df2["Which factors are most important in recommendation ? [Similarity Score]"].apply(lambda x: position_str(x))
df2["Which factors are most important in recommendation ? [Bookmark Count]"] = df2["Which factors are most important in recommendation ? [Bookmark Count]"].apply(lambda x: position_str(x))

df2.head()

,Timestamp,What is your highest degree?,Are you familiar with recommendation content?,Which factors are most important in recommendation ? [Views],Which factors are most important in recommendation ? [Creation Date],Which factors are most important in recommendation ? [Rating],Which factors are most important in recommendation ? [Similarity Score],Which factors are most important in recommendation ? [Bookmark Count],Please rank the following factors in order of importance [Row 1]
0,2024-04-20 23:26:02.873,Bachelor's degree,Yes,position(2),position(1),position(4),position(3),position(5),Column 1
1,2024-04-20 23:33:09.033,Master's degree,NaN,position(1),position(2),position(4),position(5),position(3),Column 1
2,2024-04-20 23:33:45.276,high school diploma,NaN,position(3),position(2),position(1),position(5),position(4),Column 1
3,2024-04-20 23:34:09.648,high school diploma,NaN,position(2),position(3),position(4),position(1),position(5),Column 1

In [ ]:
views_counts = df2["Which factors are most important in recommendation ? [Views]"].value_counts()
creation_date_counts = df2["Which factors are most important in recommendation ? [Creation Date]"].value_counts()
rating_counts = df2["Which factors are most important in recommendation ? [Rating]"].value_counts()
similarity_score_counts = df2["Which factors are most important in recommendation ? [Similarity Score]"].value_counts()
bookmark_counts = df2["Which factors are most important in recommendation ? [Bookmark Count]"].value_counts()

In [ ]:
views_counts_normalized = df2["Which factors are most important in recommendation ? [Views]"].value_counts(normalize=True)
creation_date_counts_normalized = df2["Which factors are most important in recommendation ? [Creation Date]"].value_counts(normalize=True)
rating_counts_normalized = df2["Which factors are most important in recommendation ? [Rating]"].value_counts(normalize=True)
similarity_score_counts_normalized = df2["Which factors are most important in recommendation ? [Similarity Score]"].value_counts(normalize=True)
bookmark_counts_normalized = df2["Which factors are most important in recommendation ? [Bookmark Count]"].value_counts(normalize=True)

In [ ]:
print("Total User:", df2.shape[0])
print("views:", get_key_and_value_counts(views_counts))
print("creation date:", get_key_and_value_counts(creation_date_counts))
print("rating:", get_key_and_value_counts(rating_counts))
print("similarity score:", get_key_and_value_counts(similarity_score_counts))
print("bookmark:", get_key_and_value_counts(bookmark_counts))

Total User: 4
views: {'position(2)': 2, 'position(1)': 1, 'position(3)': 1}
creation date: {'position(2)': 2, 'position(1)': 1, 'position(3)': 1}
rating: {'position(4)': 3, 'position(1)': 1}
similarity score: {'position(5)': 2, 'position(3)': 1, 'position(1)': 1}
bookmark: {'position(5)': 2, 'position(3)': 1, 'position(4)': 1}

In [ ]:
print("Total User:", df2.shape[0])
print("views:", get_key_and_value_counts(views_counts_normalized))
print("creation date:", get_key_and_value_counts(creation_date_counts_normalized))
print("rating:", get_key_and_value_counts(rating_counts_normalized))
print("similarity score:", get_key_and_value_counts(similarity_score_counts_normalized))
print("bookmark:", get_key_and_value_counts(bookmark_counts_normalized))

Total User: 4
views: {'position(2)': 0.5, 'position(1)': 0.25, 'position(3)': 0.25}
creation date: {'position(2)': 0.5, 'position(1)': 0.25, 'position(3)': 0.25}
rating: {'position(4)': 0.75, 'position(1)': 0.25}
similarity score: {'position(5)': 0.5, 'position(3)': 0.25, 'position(1)': 0.25}
bookmark: {'position(5)': 0.5, 'position(3)': 0.25, 'position(4)': 0.25}